//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cliente()
        {
            this.tbl_mascotas = new HashSet<tbl_mascotas>();
        }
    
        public string id_c { get; set; }
        public string nombre_c { get; set; }
        public string apellido_c { get; set; }
        public string edad_c { get; set; }
        public System.DateTime fecha_nacimiento_c { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mascotas> tbl_mascotas { get; set; }
    }
}
