//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_factura()
        {
            this.tbl_productos = new HashSet<tbl_productos>();
            this.tbl_servicio = new HashSet<tbl_servicio>();
        }
    
        public string codigo_f { get; set; }
        public System.DateTime fecha_f { get; set; }
        public string id_m { get; set; }
        public string codigo_pfl { get; set; }
    
        public virtual tbl_profesional tbl_profesional { get; set; }
        public virtual tbl_mascotas tbl_mascotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productos> tbl_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_servicio> tbl_servicio { get; set; }
    }
}
