//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_veterinariaEntities : DbContext
    {
        public db_veterinariaEntities()
            : base("name=db_veterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cliente> tbl_cliente { get; set; }
        public virtual DbSet<tbl_especie> tbl_especie { get; set; }
        public virtual DbSet<tbl_factura> tbl_factura { get; set; }
        public virtual DbSet<tbl_mascotas> tbl_mascotas { get; set; }
        public virtual DbSet<tbl_productos> tbl_productos { get; set; }
        public virtual DbSet<tbl_profesional> tbl_profesional { get; set; }
        public virtual DbSet<tbl_raza> tbl_raza { get; set; }
        public virtual DbSet<tbl_servicio> tbl_servicio { get; set; }
        public virtual DbSet<tbl_tipo_producto> tbl_tipo_producto { get; set; }
    
        public virtual int pa_delete_cliente(string pa_id)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_cliente", pa_idParameter);
        }
    
        public virtual int pa_delete_especie(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_especie", pa_codigoParameter);
        }
    
        public virtual int pa_delete_factura(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_factura", pa_codigoParameter);
        }
    
        public virtual int pa_delete_factura_producto(string pa_codigo_f)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_factura_producto", pa_codigo_fParameter);
        }
    
        public virtual int pa_delete_factura_servicio(string pa_codigo_f)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_factura_servicio", pa_codigo_fParameter);
        }
    
        public virtual int pa_delete_mascota(string pa_id)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_mascota", pa_idParameter);
        }
    
        public virtual int pa_delete_productos(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_productos", pa_codigoParameter);
        }
    
        public virtual int pa_delete_profesional(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_profesional", pa_codigoParameter);
        }
    
        public virtual int pa_delete_raza(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_raza", pa_codigoParameter);
        }
    
        public virtual int pa_delete_servicio(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_servicio", pa_codigoParameter);
        }
    
        public virtual int pa_delete_tipo_producto(string pa_codigo)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_delete_tipo_producto", pa_codigoParameter);
        }
    
        public virtual int pa_insert_cliente(string pa_id, string pa_nombre, string pa_apellido, string pa_edad, Nullable<System.DateTime> pa_fecha_nacimiento)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_apellidoParameter = pa_apellido != null ?
                new ObjectParameter("pa_apellido", pa_apellido) :
                new ObjectParameter("pa_apellido", typeof(string));
    
            var pa_edadParameter = pa_edad != null ?
                new ObjectParameter("pa_edad", pa_edad) :
                new ObjectParameter("pa_edad", typeof(string));
    
            var pa_fecha_nacimientoParameter = pa_fecha_nacimiento.HasValue ?
                new ObjectParameter("pa_fecha_nacimiento", pa_fecha_nacimiento) :
                new ObjectParameter("pa_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_cliente", pa_idParameter, pa_nombreParameter, pa_apellidoParameter, pa_edadParameter, pa_fecha_nacimientoParameter);
        }
    
        public virtual int pa_insert_especie(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_especie", pa_codigoParameter, pa_nombreParameter);
        }
    
        public virtual int pa_insert_factura(string pa_codigo, Nullable<System.DateTime> pa_fecha, string pa_id_m, string pa_codigo_pfl)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_fechaParameter = pa_fecha.HasValue ?
                new ObjectParameter("pa_fecha", pa_fecha) :
                new ObjectParameter("pa_fecha", typeof(System.DateTime));
    
            var pa_id_mParameter = pa_id_m != null ?
                new ObjectParameter("pa_id_m", pa_id_m) :
                new ObjectParameter("pa_id_m", typeof(string));
    
            var pa_codigo_pflParameter = pa_codigo_pfl != null ?
                new ObjectParameter("pa_codigo_pfl", pa_codigo_pfl) :
                new ObjectParameter("pa_codigo_pfl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_factura", pa_codigoParameter, pa_fechaParameter, pa_id_mParameter, pa_codigo_pflParameter);
        }
    
        public virtual int pa_insert_factura_producto(string pa_codigo_f, string pa_codigo_pd)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            var pa_codigo_pdParameter = pa_codigo_pd != null ?
                new ObjectParameter("pa_codigo_pd", pa_codigo_pd) :
                new ObjectParameter("pa_codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_factura_producto", pa_codigo_fParameter, pa_codigo_pdParameter);
        }
    
        public virtual int pa_insert_factura_servicio(string pa_codigo_f, string pa_codigo_s)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            var pa_codigo_sParameter = pa_codigo_s != null ?
                new ObjectParameter("pa_codigo_s", pa_codigo_s) :
                new ObjectParameter("pa_codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_factura_servicio", pa_codigo_fParameter, pa_codigo_sParameter);
        }
    
        public virtual int pa_insert_mascota(string pa_id, string pa_nombre, string pa_descripcion, string pa_edad, string pa_sexo, Nullable<System.DateTime> pa_fecha_nacimiento, string pa_codigo_e, string pa_id_c, string pa_codigo_r)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_descripcionParameter = pa_descripcion != null ?
                new ObjectParameter("pa_descripcion", pa_descripcion) :
                new ObjectParameter("pa_descripcion", typeof(string));
    
            var pa_edadParameter = pa_edad != null ?
                new ObjectParameter("pa_edad", pa_edad) :
                new ObjectParameter("pa_edad", typeof(string));
    
            var pa_sexoParameter = pa_sexo != null ?
                new ObjectParameter("pa_sexo", pa_sexo) :
                new ObjectParameter("pa_sexo", typeof(string));
    
            var pa_fecha_nacimientoParameter = pa_fecha_nacimiento.HasValue ?
                new ObjectParameter("pa_fecha_nacimiento", pa_fecha_nacimiento) :
                new ObjectParameter("pa_fecha_nacimiento", typeof(System.DateTime));
    
            var pa_codigo_eParameter = pa_codigo_e != null ?
                new ObjectParameter("pa_codigo_e", pa_codigo_e) :
                new ObjectParameter("pa_codigo_e", typeof(string));
    
            var pa_id_cParameter = pa_id_c != null ?
                new ObjectParameter("pa_id_c", pa_id_c) :
                new ObjectParameter("pa_id_c", typeof(string));
    
            var pa_codigo_rParameter = pa_codigo_r != null ?
                new ObjectParameter("pa_codigo_r", pa_codigo_r) :
                new ObjectParameter("pa_codigo_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_mascota", pa_idParameter, pa_nombreParameter, pa_descripcionParameter, pa_edadParameter, pa_sexoParameter, pa_fecha_nacimientoParameter, pa_codigo_eParameter, pa_id_cParameter, pa_codigo_rParameter);
        }
    
        public virtual int pa_insert_productos(string pa_codigo, string pa_nombre, Nullable<double> pa_precio, string pa_codigo_tp)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_precioParameter = pa_precio.HasValue ?
                new ObjectParameter("pa_precio", pa_precio) :
                new ObjectParameter("pa_precio", typeof(double));
    
            var pa_codigo_tpParameter = pa_codigo_tp != null ?
                new ObjectParameter("pa_codigo_tp", pa_codigo_tp) :
                new ObjectParameter("pa_codigo_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_productos", pa_codigoParameter, pa_nombreParameter, pa_precioParameter, pa_codigo_tpParameter);
        }
    
        public virtual int pa_insert_profesional(string pa_codigo, string pa_nombre, string pa_apellido, string pa_telefono, string pa_celular)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_apellidoParameter = pa_apellido != null ?
                new ObjectParameter("pa_apellido", pa_apellido) :
                new ObjectParameter("pa_apellido", typeof(string));
    
            var pa_telefonoParameter = pa_telefono != null ?
                new ObjectParameter("pa_telefono", pa_telefono) :
                new ObjectParameter("pa_telefono", typeof(string));
    
            var pa_celularParameter = pa_celular != null ?
                new ObjectParameter("pa_celular", pa_celular) :
                new ObjectParameter("pa_celular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_profesional", pa_codigoParameter, pa_nombreParameter, pa_apellidoParameter, pa_telefonoParameter, pa_celularParameter);
        }
    
        public virtual int pa_insert_raza(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_raza", pa_codigoParameter, pa_nombreParameter);
        }
    
        public virtual int pa_insert_servicio(string pa_codigo, string pa_nombre, string pa_descripcion, Nullable<double> pa_precio)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_descripcionParameter = pa_descripcion != null ?
                new ObjectParameter("pa_descripcion", pa_descripcion) :
                new ObjectParameter("pa_descripcion", typeof(string));
    
            var pa_precioParameter = pa_precio.HasValue ?
                new ObjectParameter("pa_precio", pa_precio) :
                new ObjectParameter("pa_precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_servicio", pa_codigoParameter, pa_nombreParameter, pa_descripcionParameter, pa_precioParameter);
        }
    
        public virtual int pa_insert_tipo_producto(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_insert_tipo_producto", pa_codigoParameter, pa_nombreParameter);
        }
    
        public virtual ObjectResult<pa_select_cliente_Result> pa_select_cliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_cliente_Result>("pa_select_cliente");
        }
    
        public virtual ObjectResult<pa_select_especie_Result> pa_select_especie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_especie_Result>("pa_select_especie");
        }
    
        public virtual ObjectResult<pa_select_factura_Result> pa_select_factura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_factura_Result>("pa_select_factura");
        }
    
        public virtual ObjectResult<pa_select_factura_producto_Result> pa_select_factura_producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_factura_producto_Result>("pa_select_factura_producto");
        }
    
        public virtual ObjectResult<pa_select_factura_servicio_Result> pa_select_factura_servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_factura_servicio_Result>("pa_select_factura_servicio");
        }
    
        public virtual ObjectResult<pa_select_mascota_Result> pa_select_mascota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_mascota_Result>("pa_select_mascota");
        }
    
        public virtual ObjectResult<pa_select_productos_Result> pa_select_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_productos_Result>("pa_select_productos");
        }
    
        public virtual ObjectResult<pa_select_profesional_Result> pa_select_profesional()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_profesional_Result>("pa_select_profesional");
        }
    
        public virtual ObjectResult<pa_select_raza_Result> pa_select_raza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_raza_Result>("pa_select_raza");
        }
    
        public virtual ObjectResult<pa_select_servicio_Result> pa_select_servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_servicio_Result>("pa_select_servicio");
        }
    
        public virtual ObjectResult<pa_select_tipo_producto_Result> pa_select_tipo_producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_select_tipo_producto_Result>("pa_select_tipo_producto");
        }
    
        public virtual int pa_update_cliente(string pa_id, string pa_nombre, string pa_apellido, string pa_edad, Nullable<System.DateTime> pa_fecha_nacimiento)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_apellidoParameter = pa_apellido != null ?
                new ObjectParameter("pa_apellido", pa_apellido) :
                new ObjectParameter("pa_apellido", typeof(string));
    
            var pa_edadParameter = pa_edad != null ?
                new ObjectParameter("pa_edad", pa_edad) :
                new ObjectParameter("pa_edad", typeof(string));
    
            var pa_fecha_nacimientoParameter = pa_fecha_nacimiento.HasValue ?
                new ObjectParameter("pa_fecha_nacimiento", pa_fecha_nacimiento) :
                new ObjectParameter("pa_fecha_nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_cliente", pa_idParameter, pa_nombreParameter, pa_apellidoParameter, pa_edadParameter, pa_fecha_nacimientoParameter);
        }
    
        public virtual int pa_update_especie(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_especie", pa_codigoParameter, pa_nombreParameter);
        }
    
        public virtual int pa_update_factura(string pa_codigo, Nullable<System.DateTime> pa_fecha, string pa_id_m, string pa_codigo_pfl)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_fechaParameter = pa_fecha.HasValue ?
                new ObjectParameter("pa_fecha", pa_fecha) :
                new ObjectParameter("pa_fecha", typeof(System.DateTime));
    
            var pa_id_mParameter = pa_id_m != null ?
                new ObjectParameter("pa_id_m", pa_id_m) :
                new ObjectParameter("pa_id_m", typeof(string));
    
            var pa_codigo_pflParameter = pa_codigo_pfl != null ?
                new ObjectParameter("pa_codigo_pfl", pa_codigo_pfl) :
                new ObjectParameter("pa_codigo_pfl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_factura", pa_codigoParameter, pa_fechaParameter, pa_id_mParameter, pa_codigo_pflParameter);
        }
    
        public virtual int pa_update_factura_producto(string pa_codigo_f, string pa_codigo_pd)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            var pa_codigo_pdParameter = pa_codigo_pd != null ?
                new ObjectParameter("pa_codigo_pd", pa_codigo_pd) :
                new ObjectParameter("pa_codigo_pd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_factura_producto", pa_codigo_fParameter, pa_codigo_pdParameter);
        }
    
        public virtual int pa_update_factura_servicio(string pa_codigo_f, string pa_codigo_s)
        {
            var pa_codigo_fParameter = pa_codigo_f != null ?
                new ObjectParameter("pa_codigo_f", pa_codigo_f) :
                new ObjectParameter("pa_codigo_f", typeof(string));
    
            var pa_codigo_sParameter = pa_codigo_s != null ?
                new ObjectParameter("pa_codigo_s", pa_codigo_s) :
                new ObjectParameter("pa_codigo_s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_factura_servicio", pa_codigo_fParameter, pa_codigo_sParameter);
        }
    
        public virtual int pa_update_mascota(string pa_id, string pa_nombre, string pa_descripcion, string pa_edad, string pa_sexo, Nullable<System.DateTime> pa_fecha_nacimiento, string pa_codigo, string pa_id_c, string pa_codigo_r)
        {
            var pa_idParameter = pa_id != null ?
                new ObjectParameter("pa_id", pa_id) :
                new ObjectParameter("pa_id", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_descripcionParameter = pa_descripcion != null ?
                new ObjectParameter("pa_descripcion", pa_descripcion) :
                new ObjectParameter("pa_descripcion", typeof(string));
    
            var pa_edadParameter = pa_edad != null ?
                new ObjectParameter("pa_edad", pa_edad) :
                new ObjectParameter("pa_edad", typeof(string));
    
            var pa_sexoParameter = pa_sexo != null ?
                new ObjectParameter("pa_sexo", pa_sexo) :
                new ObjectParameter("pa_sexo", typeof(string));
    
            var pa_fecha_nacimientoParameter = pa_fecha_nacimiento.HasValue ?
                new ObjectParameter("pa_fecha_nacimiento", pa_fecha_nacimiento) :
                new ObjectParameter("pa_fecha_nacimiento", typeof(System.DateTime));
    
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_id_cParameter = pa_id_c != null ?
                new ObjectParameter("pa_id_c", pa_id_c) :
                new ObjectParameter("pa_id_c", typeof(string));
    
            var pa_codigo_rParameter = pa_codigo_r != null ?
                new ObjectParameter("pa_codigo_r", pa_codigo_r) :
                new ObjectParameter("pa_codigo_r", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_mascota", pa_idParameter, pa_nombreParameter, pa_descripcionParameter, pa_edadParameter, pa_sexoParameter, pa_fecha_nacimientoParameter, pa_codigoParameter, pa_id_cParameter, pa_codigo_rParameter);
        }
    
        public virtual int pa_update_productos(string pa_codigo, string pa_nombre, Nullable<double> pa_precio, string pa_codigo_tp)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_precioParameter = pa_precio.HasValue ?
                new ObjectParameter("pa_precio", pa_precio) :
                new ObjectParameter("pa_precio", typeof(double));
    
            var pa_codigo_tpParameter = pa_codigo_tp != null ?
                new ObjectParameter("pa_codigo_tp", pa_codigo_tp) :
                new ObjectParameter("pa_codigo_tp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_productos", pa_codigoParameter, pa_nombreParameter, pa_precioParameter, pa_codigo_tpParameter);
        }
    
        public virtual int pa_update_profesional(string pa_codigo, string pa_nombre, string pa_apellido, string pa_telefono, string pa_celular)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_apellidoParameter = pa_apellido != null ?
                new ObjectParameter("pa_apellido", pa_apellido) :
                new ObjectParameter("pa_apellido", typeof(string));
    
            var pa_telefonoParameter = pa_telefono != null ?
                new ObjectParameter("pa_telefono", pa_telefono) :
                new ObjectParameter("pa_telefono", typeof(string));
    
            var pa_celularParameter = pa_celular != null ?
                new ObjectParameter("pa_celular", pa_celular) :
                new ObjectParameter("pa_celular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_profesional", pa_codigoParameter, pa_nombreParameter, pa_apellidoParameter, pa_telefonoParameter, pa_celularParameter);
        }
    
        public virtual int pa_update_raza(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_raza", pa_codigoParameter, pa_nombreParameter);
        }
    
        public virtual int pa_update_servicio(string pa_codigo, string pa_nombre, string pa_descripcion, Nullable<double> pa_precio)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            var pa_descripcionParameter = pa_descripcion != null ?
                new ObjectParameter("pa_descripcion", pa_descripcion) :
                new ObjectParameter("pa_descripcion", typeof(string));
    
            var pa_precioParameter = pa_precio.HasValue ?
                new ObjectParameter("pa_precio", pa_precio) :
                new ObjectParameter("pa_precio", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_servicio", pa_codigoParameter, pa_nombreParameter, pa_descripcionParameter, pa_precioParameter);
        }
    
        public virtual int pa_update_tipo_producto(string pa_codigo, string pa_nombre)
        {
            var pa_codigoParameter = pa_codigo != null ?
                new ObjectParameter("pa_codigo", pa_codigo) :
                new ObjectParameter("pa_codigo", typeof(string));
    
            var pa_nombreParameter = pa_nombre != null ?
                new ObjectParameter("pa_nombre", pa_nombre) :
                new ObjectParameter("pa_nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_update_tipo_producto", pa_codigoParameter, pa_nombreParameter);
        }
    }
}
